
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://jeg114.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Jesus Erlantz Garcia Condado"
title: "{ Jesus E. Garcia}"
description: "Welcome to my portfolio, a space to share some background on myself, my story, my puspose and my ambitions"
keywords: "Jesus, Erlantz, Garcia, portfolio, cv"
favicon: "/img/pirate_favicon.ico"

################
# Header layout #
################

black-favicon: "/img/pirate_favicon.ico"

background-img: "../img/bilbao_at_night.jpeg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: False
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hi! Its Jesus, welcome to my portfolio"
  - text: "Here you can find some of the highlights of my carreer path."
  - text: "I chose engineering to "

me-img: "/img/face.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Projects #
########

enable-gesture-navigation: True

post-preview-words: 120

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: false
google-plus-share: True
tumblr-share: false
pinterest-share: false
pocket-share: false
vkontakte-share: false

disqus-shortname: "jesus_e_garcia"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "April 2017"
    description: "Rejoined ARM for 6 month placement as part of my degree"
  - image: "/img/timeline/spidertocat.png"
    date: "July 2016"
    description: "Obtained UKESF scholarship sponsored by ARM and joined them for summer internship"
  - image: "/img/timeline/spidertocat.png"
    date: "October 2014"
    description: "Started MEng in Electronic and Information Engineering (graduating 2018)"
  - image: "/img/timeline/baracktocat.jpg"
    date: "June 2014"
    description: "Graduated from music school in Piano"
  - image: "/img/timeline/baracktocat.jpg"
    date: "June 2014"
    description: "Graduated from the American School of Bilbao"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "jesus.garcia-condado14@imperial.ac.uk"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Jesus E. Garcia is a student in "
author_blurb_image: "/img/full_body.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "linkedin"
    url: "https://linkedin.com/"
  - title: "github"
    url: "https://github.com/jeg114"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: ""
keybase-in-social: false
keybase-in-footer: false

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Projects: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
